name: PixelVip
main: br.net.fabiozumbi12.PixelVip.PixelVip
version: ${project.version}
author: FabioZumbi12
description: ${project.description}
softdepend: [Vault, Essentials, PagSeguroAPI]
commands:
  pixelvip:
    description: "Main command for PixelVip."
    permission: "pixelvip.cmd.pixelvip"
    usage: "/pixelvip reload|fileToMysql|mysqlToFile"
  newitemkey:
    description: "Generate new item key for commands."
    permission: "pixelvip.cmd.newitemkey"
    usage: "/newitemkey <cmd1, cmd2, ...>"
    aliases: [genitemkey, geraritemkey, newikey, gerarikey]
  additemkey:
    description: "Add commands to a key."
    permission: "pixelvip.cmd.additemkey"
    usage: "/additemkey <key> <cmd>"
    aliases: [addikey, aikey]
  delkey:
    description: "Remove a key."
    permission: "pixelvip.cmd.delkey"
    usage: "/delkey <key>"
    aliases: [removekey, dkey, rkey]
  newkey:
    description: "Generate new vip key for groups."
    permission: "pixelvip.cmd.newkey"
    usage: "/newkey <vip group> <days> [uses]"
    aliases: [genkey, gerarkey]
  listkeys:
    description: "List all available keys."
    permission: "pixelvip.cmd.listkeys"
    usage: "/listkeys"
    aliases: [listarkeys]
  usekey:
    description: "Use a key to activate the Vip."
    permission: "pixelvip.cmd.player"
    usage: "/usekey <key>"
    aliases: [usarkey]
  viptime:
    description: "Use to check the vip time."
    permission: "pixelvip.cmd.player"
    usage: "/viptime"
    aliases: [tempovip]
  removevip:
    description: "Use to remove a vip of player."
    permission: "pixelvip.cmd.removevip"
    usage: "/removevip <player> [vip group]"
    aliases: [delvip]
  setactive:
    description: "Use to change your active VIP, if more keys activated."
    permission: "pixelvip.cmd.player"
    usage: "/setactive <vip group>"
    aliases: [changevip, trocarvip]
  addvip:
    description: "Use to add a vip for a player without key."
    permission: "pixelvip.cmd.addvip"
    usage: "/addvip <player> <vip group> <days>"
    aliases: [givevip, darvip]
  setvip:
    description: "Use to set a vip without activation and without key."
    permission: "pixelvip.cmd.setvip"
    usage: "/setvip <player> <vip group> <days>"
    aliases: []
  listvips:
    description: "List all active vips of server."
    permission: "pixelvip.cmd.listvips"
    usage: "/listvips"
    aliases: []
permissions:
  pixelvip.normal:
    description: "Player commands."
    default: true
    children:
      pixelvip.cmd.player: true
  pixelvip.admin:
    description: "Admin commands."
    default: op
    children:
      pixelvip.cmd.player: true
      pixelvip.cmd.player.others: true
      pixelvip.cmd.newkey: true
      pixelvip.cmd.delkey: true
      pixelvip.cmd.newitemkey: true
      pixelvip.cmd.additemkey: true
      pixelvip.cmd.listkeys: true
      pixelvip.cmd.removevip: true
      pixelvip.cmd.addvip: true
      pixelvip.cmd.setvip: true
      pixelvip.cmd.listvips: true